theme: ./src

siteConfig:
  url: https://callumflack.design
  author: Callum Flack
  email: callum@callumflack.design
  phone: +61(0) 408 767 540
  title: Callum Flack Design
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.
  social:
    twitter: callumflack
    github: callumflack

themeConfig:
  nav:
    - text: projects
      link: /projects.html
    - text: writing
      link: /writing.html
    - text: about
      link: /about.html
  social:
    rss: true
  lang: en

permalinks:
  post: /blog/:slug.html

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  - resolve: saber-plugin-critical
  - resolve: saber-plugin-netlify-redirect
  # - resolve: 'saber-plugin-google-analytics'
  #     options:
  #       trackId: 'UA-54857209-19'

markdown:
  plugins:
    - resolve: markdown-it-attrs
    - resolve: markdown-it-sup
