theme: ../src

siteConfig:
  url: https://callumflack.design
  author: Callum Flack
  email: callum@callumflack.design
  phone: +61(0) 408 767 540
  title: CFd
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.
  social:
    twitter: callumflack
    github: callumflack

themeConfig:
  nav:
    - text: Projects
      link: /projects.html
    - text: Writing
      link: /writing.html
    - text: About
      link: /about.html
  social:
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  - resolve: saber-plugin-critical
